Repository reactioncommerce/reaction-component-library, pull requests merged in 2018-09, with the labels that each got.

#285 feat: added initailSize prop for SSR
  package/src/components/CatalogGrid/v1/CatalogGrid.js
Labels: enhancement

#289 fix: 283 nnnnat viewerinfo
  package/src/components/ViewerInfo/v1/ViewerInfo.js
  package/src/components/ViewerInfo/v1/ViewerInfo.md
  package/src/components/ViewerInfo/v1/ViewerInfo.test.js
  package/src/components/ViewerInfo/v1/__snapshots__/ViewerInfo.test.js.snap
  package/src/defaultComponentTheme.js
Labels: bug, enhancement

#292 refactor: nnnnat viewerinfo
  package/src/components/ViewerInfo/v1/ViewerInfo.js
  package/src/components/ViewerInfo/v1/ViewerInfo.md
  package/src/components/ViewerInfo/v1/ViewerInfo.test.js
  package/src/components/ViewerInfo/v1/__snapshots__/ViewerInfo.test.js.snap
Labels: bug, enhancement

#296 Fix checkout actions: remove unnecessary re-render
  package/src/components/CheckoutActions/v1/CheckoutActions.js
  package/src/components/CheckoutActions/v1/CheckoutActions.md
Labels: bug

#298 fix: added padding to MiniCart, only when mini
  package/src/components/CartItem/v1/CartItem.js
  package/src/components/CartItem/v1/__snapshots__/CartItem.test.js.snap
  package/src/components/CartSummary/v1/CartSummary.js
  package/src/components/CartSummary/v1/__snapshots__/CartSummary.test.js.snap
  package/src/components/FinalReviewCheckoutAction/v1/FinalReviewCheckoutAction.js
  package/src/components/FinalReviewCheckoutAction/v1/__snapshots__/FinalReviewCheckoutAction.test.js.snap
  package/src/components/MiniCart/v1/MiniCart.js
  package/src/components/MiniCart/v1/__snapshots__/MiniCart.test.js.snap
  package/src/defaultComponentTheme.js
Labels: bug
